# Generated by Django 4.1.1 on 2022-09-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("wikipedia", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("summary", models.TextField(blank=True)),
                ("stock", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Av", "Aventure"),
                            ("Th", "Thriller"),
                            ("Fa", "Fantastique"),
                            ("Ro", "Romance"),
                            ("Ho", "Horreur"),
                            ("Sf", "Science-fiction"),
                        ],
                        default="Av",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionlivre.author",
                    ),
                ),
            ],
        ),
    ]
